server:
  port: 10000

#logging:
#  file:
#    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
#  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
#    com.example.springboot.batch : debug
spring:
  datasource:
    h2:
      jdbcUrl: jdbc:h2:tcp://localhost/~/test
      driverClassName: org.h2.Driver
      username: sa
      password:
#    sqlite:
#      jdbcUrl: jdbc:sqlite:identifier.sqlite
#      driverClassName: org.sqlite.JDBC
#      username:
#      password:
    oracle:
      jdbcUrl: jdbc:oracle:thin:@165.243.45.87:1521:MTRONDEV
      driverClassName: oracle.jdbc.driver.OracleDriver
      username: emro
      password: emro
    mssql:
      jdbcUrl: jdbc:sqlserver://10.155.9.50:1433;databaseName=EPRO
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: emro
      password: lsm@dminPassw0rd.
  batch:
    job:
      enabled: true